# Generated by Django 5.1.2 on 2024-11-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicturesofall'),
        ),
    ]
