# Generated by Django 5.1.2 on 2024-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='joiningdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_bio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
